name = "acajankovic"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_SANITY_PROJECT_ID = "1s30e0de"
NEXT_PUBLIC_SANITY_DATASET = "production"
NEXT_PUBLIC_SANITY_API_VERSION = "2024-01-01"
NEXT_PUBLIC_SITE_URL = "https://acajankovic.karacdev.workers.dev"
